import { chromium } from '@playwright/test';
const b = await chromium.launch({ channel: 'chromium', args: ['--enable-unsafe-webgpu'] });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://127.0.0.1:8772/PowerStudio.html?sample=ieee14');
await p.waitForFunction(() => window.powerstudio?.ready);
await p.locator('.toast').evaluateAll(t => t.forEach(x => x.remove()));
await p.locator('.ribbon-tab[data-tab="file"]').click();
await p.waitForTimeout(300);
await p.screenshot({ path: process.argv[2] + '/bs1.png' });
await p.locator('.backstage nav [data-page="about"]').click();
await p.waitForTimeout(200);
await p.screenshot({ path: process.argv[2] + '/bs2.png' });
await p.keyboard.press('Escape');
const vb = await p.locator('#viewport').boundingBox();
await p.mouse.click(vb.x + vb.width / 2, vb.y + vb.height / 2, { button: 'right' });
await p.waitForTimeout(200);
await p.screenshot({ path: process.argv[2] + '/menu.png' });
console.log(errs);
await b.close();
