[package]
name = "ps-sparse"
description = "Sparse matrices and direct solvers for the PowerStudio engine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
faer.workspace = true
ps-num.workspace = true

[lints]
workspace = true
